version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x # Optional, if Python is needed for scripts
    commands:
      - echo "Installing Terraform for ARM64..."
      - curl -O https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_arm64.zip
      - unzip terraform_1.5.6_linux_arm64.zip
      - chmod +x terraform
      - mkdir -p /tmp/bin
      - mv terraform /tmp/bin/
      - export PATH=$PATH:/tmp/bin
      - terraform --version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Validating Terraform files..."
      - terraform validate

  build:
    commands:
      - echo "Planning infrastructure changes..."
      - terraform plan -out=tfplan
      - echo "Applying infrastructure changes..."
      - terraform destroy
      
  post_build:
    commands:
      - echo "Cleaning up..."
      - rm -rf tfplan
      - echo "Build and resource creation completed!"

      
artifacts:
  files:
    - "**/*"
  discard-paths: yes
